iname: Release Build

permissions:
  contents: write
  packages: read
  actions: read

on:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+" # Trigger on semantic version tags

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create_release:
    name: Create GitHub Release
    permissions:
      contents: write
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: true # Set to false for production releases

  build-and-release:
    name: Build and Upload Release Asset
    needs: create_release
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - nix_system: x86_64-linux
            runner: ubuntu-latest
          - nix_system: aarch64-linux
            runner: ubuntu-24.04-arm
          - nix_system: x86_64-darwin
            runner: macos-latest
          - nix_system: aarch64-darwin
            runner: macos-latest
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes configurable-impure-env auto-allocate-uids
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Set Environment Variables
        run: echo "CACHIX_AUTH_TOKEN=${{ secrets.CACHIX_AUTH_TOKEN }}" >> $GITHUB_ENV

      - name: Cachix Cache
        uses: cachix/cachix-action@v14
        if: env.CACHIX_AUTH_TOKEN != ''
        env:
          CACHIX_AUTH_TOKEN: ${{ env.CACHIX_AUTH_TOKEN }}
        with:
          name: nico-swan-com
          authToken: ${{ env.CACHIX_AUTH_TOKEN }}

      - name: Build with Nix
        run: |
          set -e
          nix build --option system ${{ matrix.nix_system }} .#packages.${{ matrix.nix_system }}.default -o result-${{ matrix.nix_system }}
          echo "NIX_SYSTEM=${{ matrix.nix_system }}" >> $GITHUB_ENV
          echo "BINARY_PATH=result-${{ matrix.nix_system }}/bin/git-project-updater" >> $GITHUB_ENV
          echo "RELEASE_NAME=git-project-updater-${{ matrix.nix_system }}" >> $GITHUB_ENV

      - name: Determine File Extension
        id: file_ext
        run: |
          if [[ "${{ matrix.nix_system }}" == *"-darwin"* ]]; then
            echo "EXT=.zip" >> $GITHUB_ENV
          else
            echo "EXT=.tar.gz" >> $GITHUB_ENV
          fi

      - name: Prepare Release Asset Name
        id: asset_name
        run: |
          asset_suffix=""
          case "${{ matrix.nix_system }}" in
            "x86_64-linux") asset_suffix="x86_64-unknown-linux-gnu" ;;  # "unknown" is explicitly included here.
            "aarch64-linux") asset_suffix="aarch64-unknown-linux-gnu" ;;
            "x86_64-darwin") asset_suffix="x86_64-apple-darwin" ;;
            "aarch64-darwin") asset_suffix="aarch64-apple-darwin" ;;
            *) echo "Unknown nix_system: ${{ matrix.nix_system }}" && exit 1 ;;
          esac
          echo "NAME=git-project-updater-${{ github.ref_name }}-${asset_suffix}" >> $GITHUB_OUTPUT

      - name: Package Artifact
        run: |
          ASSET_NAME="${{ steps.asset_name.outputs.NAME }}${{ env.EXT }}"
          echo "Packaging binary as ${ASSET_NAME}"
          if [ "${{ env.EXT }}" = ".zip" ]; then
            zip -j "${ASSET_NAME}" result-${{ matrix.nix_system }}/bin/git-project-updater
          else
            tar -czvf "${ASSET_NAME}" -C result-${{ matrix.nix_system }} bin/git-project-updater
          fi
          echo "UPLOAD_PATH=${ASSET_NAME}" >> $GITHUB_ENV
          if [ "${{ env.EXT }}" = ".zip" ]; then
            echo "ASSET_CONTENT_TYPE=application/zip" >> $GITHUB_ENV
          else
            echo "ASSET_CONTENT_TYPE=application/gzip" >> $GITHUB_ENV
          fi

      # Uncomment the following step if you wish to push new build outputs to Cachix.
      # - name: Push Build to Cachix
      #   run: |
      #     cachix push nico-swan-com result-${{ matrix.nix_system }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{ env.UPLOAD_PATH }}
          asset_name: ${{ steps.asset_name.outputs.NAME }}${{ env.EXT }}
          asset_content_type: ${{ env.ASSET_CONTENT_TYPE }}
